//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18063
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _53Project5.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("_53Project5.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 15
        ///1
        ///......xx..
        ///.....xxxx.
        ///....xx..xx
        ///....x....x
        ///....x....x
        ///....x....x
        ///....x...xx
        ///.xxxx...x.
        ///xxxxx.....
        ///.xxx......
        ///2
        ///....xx....
        ///...xxxx...
        ///..xxxxxx..
        ///.xxxxxxxx.
        ///xxxxxxxxxx
        ///xxxxxxxxxx
        ///xxxxxxxxxx
        ///.xx.xx.xx.
        ///...xxxx...
        ///..xxxxxx..
        ///3
        ///.xxx..xxx.
        ///xxxxxxxxxx
        ///xxxxxxxxxx
        ///xx.xxxxxxx
        ///xx.xxxxxxx
        ///.xx.xxxxx.
        ///.xxxxxxxx.
        ///..xxxxxx..
        ///...xxxx...
        ///....xx....
        ///4
        ///....xx....
        ///...xxxx...
        ///..xxxxxx..
        ///.xx.xx.xx.
        ///xxxxxxxxxx
        ///xxxxxxxxxx
        ///xxxxxxxxxx
        ///.xx.xx.xx.
        ///....xx....
        ///..xxxxxx..
        ///5
        ///...xxxx...
        ///. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string pics {
            get {
                return ResourceManager.GetString("pics", resourceCulture);
            }
        }
    }
}
